/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Classes.MyConnection;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author leokn
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l_ID = new javax.swing.JLabel();
        l_Motherboard = new javax.swing.JLabel();
        textFieldMotherboard = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        textFieldID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        l_Ram = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        textFieldRam = new javax.swing.JTextField();
        textFieldProcessador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        l_Grafica = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        l_Cooler = new javax.swing.JLabel();
        l_Caixa = new javax.swing.JLabel();
        l_Fonte = new javax.swing.JLabel();
        textFieldGrafica = new javax.swing.JTextField();
        textFieldCooler = new javax.swing.JTextField();
        textFieldCaixa = new javax.swing.JTextField();
        textFieldFonte = new javax.swing.JTextField();
        l_Ventoinhas = new javax.swing.JLabel();
        l_Disco = new javax.swing.JLabel();
        textFieldVentoinhas = new javax.swing.JTextField();
        textFieldDisco = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btn_sair = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tuga Compontentes");
        setLocation(new java.awt.Point(250, 300));
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(31, 81, 148));

        l_ID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_ID.setForeground(new java.awt.Color(255, 255, 255));
        l_ID.setText("Id do Product:");

        l_Motherboard.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_Motherboard.setForeground(new java.awt.Color(255, 255, 255));
        l_Motherboard.setText("Motherboard");

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/update.png"))); // NOI18N
        btn_update.setText("Atualizar");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome:");

        l_Ram.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_Ram.setForeground(new java.awt.Color(255, 255, 255));
        l_Ram.setText("Ram:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Processador:");

        l_Grafica.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_Grafica.setForeground(new java.awt.Color(255, 255, 255));
        l_Grafica.setText("Placa Gráfica:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Atualizar");

        l_Cooler.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_Cooler.setForeground(new java.awt.Color(255, 255, 255));
        l_Cooler.setText("Cooler:");

        l_Caixa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_Caixa.setForeground(new java.awt.Color(255, 255, 255));
        l_Caixa.setText("Caixa:");

        l_Fonte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_Fonte.setForeground(new java.awt.Color(255, 255, 255));
        l_Fonte.setText("Fonte de Alimentação:");

        l_Ventoinhas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_Ventoinhas.setForeground(new java.awt.Color(255, 255, 255));
        l_Ventoinhas.setText("Ventoinhas:");

        l_Disco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_Disco.setForeground(new java.awt.Color(255, 255, 255));
        l_Disco.setText("Disco:");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/update.png"))); // NOI18N

        btn_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/close.png"))); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/previous.png"))); // NOI18N
        btn_back.setText("Back");
        btn_back.setMaximumSize(new java.awt.Dimension(111, 41));
        btn_back.setMinimumSize(new java.awt.Dimension(111, 41));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addComponent(l_ID, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(textFieldProcessador, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(l_Grafica))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(84, 84, 84)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(l_Motherboard, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(l_Ram, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textFieldMotherboard, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(textFieldRam)
                                .addComponent(textFieldGrafica))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(l_Caixa)
                                    .addComponent(l_Fonte))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(92, 92, 92)
                                    .addComponent(l_Cooler)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFieldCooler, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldFonte, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(textFieldCaixa)))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(l_Disco)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textFieldDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(l_Ventoinhas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textFieldVentoinhas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(btn_update)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_Motherboard, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldMotherboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_Cooler)
                            .addComponent(textFieldCooler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_Ventoinhas)
                            .addComponent(textFieldVentoinhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(textFieldRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textFieldCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(l_Caixa)
                                        .addComponent(l_Disco)
                                        .addComponent(textFieldDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldProcessador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_Grafica)
                                    .addComponent(textFieldGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_Fonte)
                                    .addComponent(textFieldFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(l_Ram, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_update))
                        .addGap(77, 77, 77))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed


        int dialogresult = JOptionPane.showConfirmDialog(null,"Quer atualizar os seus produtos?","Warning",JOptionPane.YES_NO_CANCEL_OPTION);
        if(dialogresult == JOptionPane.YES_NO_OPTION){
            try {
                Connection con;
                MyConnection mcon = new MyConnection();
                con = mcon.returnConnection();
                String sqlquery="UPDATE Componentes SET Nome=?, Processadores=?, motherboards=?, Fonte=?, Ram=?, Grafica=?, Cooler=?, Caixas=?, Ventoinhas=?, Discos=? where ID_Pc=?";
                PreparedStatement stmt;
                stmt = con.prepareStatement(sqlquery);
                stmt.setString(1,textFieldNome.getText());
                stmt.setString(2,textFieldProcessador.getText());
                stmt.setString(3,textFieldMotherboard.getText());
                stmt.setString(4,textFieldFonte.getText());
                stmt.setString(5,textFieldRam.getText());
                stmt.setString(6,textFieldGrafica.getText());
                stmt.setString(7,textFieldCooler.getText());
                stmt.setString(8,textFieldCaixa.getText());
                stmt.setString(9,textFieldVentoinhas.getText());
                stmt.setString(10,textFieldDisco.getText());
                stmt.setString(11,textFieldID.getText());
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this,"Os produtos foram atualizados com sucesso");
                stmt.close();
                con.close();
            } catch (SQLException |HeadlessException ex) {
                JOptionPane.showMessageDialog(null,ex);
            } 
            int dialogresulto = JOptionPane.showConfirmDialog(null,"Quer voltar para a tabela dos produtos?","Warning",JOptionPane.YES_NO_CANCEL_OPTION);
            if(dialogresulto == JOptionPane.YES_NO_OPTION){
                this.dispose();
                TabelaComponentes MostraTab = new TabelaComponentes();
                MostraTab.setVisible(true);
            }   
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        int dialogresult = JOptionPane.showConfirmDialog(null,"Quer mesmo Sair?","Warning",JOptionPane.YES_NO_CANCEL_OPTION);
        if(dialogresult == JOptionPane.YES_NO_OPTION){
            System.exit(0);
            this.dispose();
        }
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.dispose();
        TabelaComponentes VoltaTabelaComponentes = new TabelaComponentes();
        VoltaTabelaComponentes.setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_Caixa;
    private javax.swing.JLabel l_Cooler;
    private javax.swing.JLabel l_Disco;
    private javax.swing.JLabel l_Fonte;
    private javax.swing.JLabel l_Grafica;
    private javax.swing.JLabel l_ID;
    private javax.swing.JLabel l_Motherboard;
    private javax.swing.JLabel l_Ram;
    private javax.swing.JLabel l_Ventoinhas;
    private javax.swing.JTextField textFieldCaixa;
    private javax.swing.JTextField textFieldCooler;
    private javax.swing.JTextField textFieldDisco;
    private javax.swing.JTextField textFieldFonte;
    private javax.swing.JTextField textFieldGrafica;
    private javax.swing.JTextField textFieldID;
    private javax.swing.JTextField textFieldMotherboard;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFieldProcessador;
    private javax.swing.JTextField textFieldRam;
    private javax.swing.JTextField textFieldVentoinhas;
    // End of variables declaration//GEN-END:variables
}
